name: Build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - uses: lukka/get-cmake@latest
      - name: Install fuse
        run: sudo apt update && sudo apt-get install -y libfuse-dev
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          RUST_TEST_THREADS: 1
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
