name: Build

on: [push]

jobs:
  test:
    env:
      RUNNER_TOOL_CACHE: /toolcache # Runner Tool Cache
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ./target
          key: build-cargo-registry

      - uses: lukka/get-cmake@latest
        with:
          useLocalCache: true
          useCloudCache: false

      - name: Install fuse
        run: sudo apt update && sudo apt-get install -y libfuse-dev
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: actions-rs/cargo@v1
        with:
          command: test

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
