name: Build

on: [push]

jobs:
  test:
    env:
      RUNNER_TOOL_CACHE: /toolcache # Runner Tool Cache
      PKG_CONFIG_SYSROOT_DIR: /
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          # - target: x86_64-unknown-linux-musl
          #   os: ubuntu-latest
          # - target: x86_64-pc-windows-msvc
          #   os: windows-latest
    steps:
      - uses: lukka/get-cmake@latest
        with:
          useLocalCache: true
          useCloudCache: false

      - name: Install fuse
        run: apt update && apt-get install -y libfuse-dev musl-tools
        if: startsWith(matrix.os, 'ubuntu')

      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "${{ matrix.target }}"

      - name: Test
        run: cargo test

      - run: echo "RUSTFLAGS=${RUSTFLAGS} -C link-args=-lpthread -C target-feature=+crt-static" >> "${GITHUB_ENV}"
        if: endsWith(matrix.target, 'musl')

      - name: Build Binary
        run: cargo build -F cli --verbose --locked --release --target ${{ matrix.target }}
