name: release-plz

permissions:
  pull-requests: write
  contents: write

on:
  push:
#     branches:
#       - master

jobs:
  release-plz:
    env:
      RUNNER_TOOL_CACHE: /toolcache # Runner Tool Cache
    name: Release-plz
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - uses: lukka/get-cmake@latest
        with:
          useLocalCache: true
          useCloudCache: false

      - name: Install fuse
        run: sudo apt update && sudo apt-get install -y libfuse-dev

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build Binary
        run: cargo build --release -F cli

      - name: Create release archive
        run: |
          mkdir dist
          cp target/release/backuppc_pool_reader dist/backuppc_pool_reader-x86_64-unknown-linux-gnu

      - name: Create binary checksum
        run: shasum --algorithm 256 --binary backuppc_pool_reader-x86_64-unknown-linux-gnu | tee backuppc_pool_reader-x86_64-unknown-linux-gnu-SHA256SUM.txt
        working-directory: ./dist

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Import GPG key
        id: import-gpg
        uses: https://github.com/crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          fingerprint: 0C69E9FC3A34B91A
          #passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      # - name: Add gitea registry in config.toml
      #   run: |
      #     echo "[registry]" >> ~/.cargo/config.toml
      #     echo "default=\"gitea\"" >> ~/.cargo/config.toml
      #     echo "[registries.gitea]" >> ~/.cargo/config.toml
      #     echo "index = \"sparse+https://gogs.shadoware.org/api/packages/phoenix/cargo/\"" >> ~/.cargo/config.toml

      - name: GPG user IDs
        run: |
          echo "fingerprint: ${{ steps.import-gpg.outputs.fingerprint }}"
          echo "keyid:       ${{ steps.import-gpg.outputs.keyid }}"
          echo "name:        ${{ steps.import-gpg.outputs.name }}"
          echo "email:       ${{ steps.import-gpg.outputs.email }}"

      - name: Release
        env:
          GITEA_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GITEA_URL: https://gogs.shadoware.org
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          CARGO_REGISTRIES_GITEA_INDEX: sparse+https://gogs.shadoware.org/api/packages/phoenix/cargo/
          CARGO_REGISTRIES_GITEA_TOKEN: ${{ secrets.CARGO_REGISTRIES_GITEA_TOKEN }}
          GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
        run: npx semantic-release
